version: '3.1'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      custom_network:
    volumes:
      - ./:/home/node/app
    ports:
      - 8080:8080

networks:
  custom_network: